# NumPy Ejercicios

#### Importar librería



In [2]:
import numpy as np

#### **Ejercicio 1:** Crear una array (unidimensional) con 10 ceros

In [3]:
#Sepuede crear una lista y convertirla en array usando np.array

lista=[0,0,0,0,0,0,0,0,0,0]
print(lista)
np.array(lista)

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [4]:
#Más sencillo, np.zeros() crea el array con el número de ceros que se le indique

np.zeros(10)            

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

Resultado esperado:
```python
array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])
```

#### **Ejercicio 2:** Crear un array (unidimensional) con 10 unos

In [5]:
#Al igual que para los ceros, en np hay una función para crear el número de unos que se le indique

np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

Resultado esperado:
```python
array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])
```

#### **Ejercicio 3:** Crear un array con 10 cincos

In [6]:
#Para crear un array de un número distinto a cero o uno, se puede usar np.ones y multiplicar por el número que queremos mostar

np.ones(10)*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

Resultado esperado:
```python
array([ 5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.])
```

#### **Ejercicio 4:** Crear un array (unidimensional) con los números enteros desde 10 hasta 50

In [7]:
#Podemos usar la función arange(), que crea el array con el rango de números que se le indique (comienzo,final) 
#El último no se incluye ya que, como siempre, comienza a contar en el índice 0
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

Resultado esperado:
```python
array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])
```

#### **Ejercicio 5:** Crear un array (unidimensional) con los enteros pares comprendidos entre 10 y 50

In [8]:
#Si queremos crear salto, usando arange(), indicamos (inicio, fin, salto)

np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

Resultado esperado:
```python
array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])
```

#### **Ejercicio 6:** Crear una matriz 3x3 con los enteros comprendidos entre 0 y 8

In [9]:
#Usamos np.arange() para crear array unidimensional entre 0 y 8
#Combinamos con reshape() para decirle las líneas y columnas que debe tener la matriz deseada

np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

Resultado esperado:
```python
array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])
```

#### **Ejercicio 7:** Crear una matriz identidad de orden 3

In [10]:
#Para la matriz de identidad que tendrá solo 0 y 1 (los 1 en diagonal), usamos la función eye() indicando el número de 1 que tendrá
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Resultado esperado:
```python
array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])
```

#### **Ejercicio 8:** Generar un número aleatorio proveniente de una distribución uniforme, entre 0 y 1

In [11]:
#Generamos aleatorios entre 0 y 1 usando random.rand(), indicando entre paréntesis cúantos valores queremos obtener. 
#Random contiene diferentes funciones para generar aleatorios. Rand genera array de valores aleatorios

np.random.rand(1)

array([0.86906282])

#### **Ejercicio 9:** Obtener 25 números aleatorios procedentes de una distribución normal estandar

In [12]:
#En este caso, la procedencia debe ser una distribución normal estándar (curva de campana, más probabilidad cerca de la media)
#La función correcta sería random.randn()

np.random.randn(25)

array([-0.96058441,  0.75862197, -0.23181398, -1.15630813,  1.04548573,
        1.04558383, -0.37127952, -0.29991022,  0.10061402, -1.04430888,
       -0.65152333,  0.50451092, -0.80049201, -0.1103014 ,  0.73609017,
        0.03711559, -0.2422328 , -1.05850734,  1.28026316, -0.01610438,
       -1.14206496,  1.25155336, -0.20906789, -0.90495718,  0.91279377])

#### ***Ejercicio 10:** Genera la siguiente matriz:
```python
array([[ 0.01,  0.02,  0.03,  0.04,  0.05,  0.06,  0.07,  0.08,  0.09,  0.1 ],
       [ 0.11,  0.12,  0.13,  0.14,  0.15,  0.16,  0.17,  0.18,  0.19,  0.2 ],
       [ 0.21,  0.22,  0.23,  0.24,  0.25,  0.26,  0.27,  0.28,  0.29,  0.3 ],
       [ 0.31,  0.32,  0.33,  0.34,  0.35,  0.36,  0.37,  0.38,  0.39,  0.4 ],
       [ 0.41,  0.42,  0.43,  0.44,  0.45,  0.46,  0.47,  0.48,  0.49,  0.5 ],
       [ 0.51,  0.52,  0.53,  0.54,  0.55,  0.56,  0.57,  0.58,  0.59,  0.6 ],
       [ 0.61,  0.62,  0.63,  0.64,  0.65,  0.66,  0.67,  0.68,  0.69,  0.7 ],
       [ 0.71,  0.72,  0.73,  0.74,  0.75,  0.76,  0.77,  0.78,  0.79,  0.8 ],
       [ 0.81,  0.82,  0.83,  0.84,  0.85,  0.86,  0.87,  0.88,  0.89,  0.9 ],
       [ 0.91,  0.92,  0.93,  0.94,  0.95,  0.96,  0.97,  0.98,  0.99,  1.  ]])
```

In [13]:
#Usamos linspace() para crear un array que vaya de un número inicial a uno final y le decimos cuántos números queremos obtener
#Combinamos con around() para redondear. Para indicar el número de decimales que nos interesa ver, lo indicamos entre paréntesis
#Finalmente usamos reshape() convertirlo en una matriz de tantas filas*tantas columnas

np.around(np.linspace(0,1,100),2).reshape(10,10)                         

array([[0.  , 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09],
       [0.1 , 0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19],
       [0.2 , 0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29],
       [0.3 , 0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39],
       [0.4 , 0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

#### **Ejercicio 11:** Crear un vector de 20 valores equidistantes entre 0 y 1

In [14]:
##Usamos linspace() para crear un array que vaya de un número inicial a uno final y le decimos cuántos puntos queremos generar
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

Resultado esperado:
```python
array([ 0.        ,  0.05263158,  0.10526316,  0.15789474,  0.21052632,
        0.26315789,  0.31578947,  0.36842105,  0.42105263,  0.47368421,
        0.52631579,  0.57894737,  0.63157895,  0.68421053,  0.73684211,
        0.78947368,  0.84210526,  0.89473684,  0.94736842,  1.        ])
```

## Numpy Indexado y filtrado

Dada la siguiente matriz, realice las operaciones pertinentes para obtener la salida que se pide:

In [15]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

**Primer ejercicio**

In [16]:
 #De mat, quiero las filas 2,3,4 (no quiero la línea 0)
 #Además quiero los números en las posiciones de la 1 al final (no quiero la posición 0)

mat[[2,3,4],1:]                      

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [17]:
#Otra forma de hacerlo: selecciona las filas desde la fila en posición 2 y todos los valores de las columnas desde el valor en posición 1

mat[2:,1:]                

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

*Resultado esperado:*


```
array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])
```



**Segundo ejercicio**

In [18]:
#De la fila 3, quiero la posición 4

mat1=mat[[3],4]     
mat1  

array([20])

In [19]:
#Otra forma de hacerlo: Fila 3,columna 4

mat[3,4]


20

*Resultado esperado:*

```
20
```



**Tercer ejercicio**

In [20]:
#De las filas 0,1,2, devuélve la posición 1
#Usamos reshape() para devolverlo en forma de matriz

mat[[0,1,2],1].reshape(3,1)                   

array([[ 2],
       [ 7],
       [12]])

In [21]:
#Otra opción:seleccionar las 3 primeras filas (0,1,2) y las columnas de la 1 a la 2 (la segunda nunca entra, así que es solo delvolverá la del índice 1)

mat[:3,1:2]          

array([[ 2],
       [ 7],
       [12]])

In [22]:
# Otra opción: selecciona las columnas de la 0 a la 3 (0,1,2) y la columna en el índice 1

mat[0:3,[1]]              

array([[ 2],
       [ 7],
       [12]])

*Resultado esperado:*

```
array([[ 2],
       [ 7],
       [12]])
```



**Cuarto ejercicio**

In [23]:
#Obtener la fila 4

mat[4]           

array([21, 22, 23, 24, 25])

*Resultado esperado:*


```
array([21, 22, 23, 24, 25])
```



**Quinto ejercicio**

In [24]:
#obtener las filas 3 y 4, de principio a fin (queremos todos los números de las filas así que solo ponemos dos puntos) 

mat[[3,4],:]                  

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

*Resultado esperado:*


```python
array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])
```



### Realice los siguiente cálculos:

#### Obtenga la suma de todos los valores de la matriz

In [25]:
#Método corto con numpy: usando función sum() de la matriz

np.sum(mat)                             

325

In [26]:
 #Método largo
 
 #Iniciar contador
suma=0                                        

for fila in mat:                  #pasar por cada fila
    for elemento in fila:         #pasar por cada elemento de cada fila
        suma=suma+elemento        #sumar cada elemento a la suma inicial (suma)
            
 
print(suma)                       #Mostrar resultado

325


*Resultado esperado:*


```python
325
```

#### Calcule la desviación típica de los valores de la matriz

In [27]:
 #Método cortocon numpy: usando la función std() de la matriz

np.std(mat)                            

7.211102550927978

*Resultado esperado:*


```python
7.211102550927978
```

#### Sume los valores por columnas



In [28]:
#Con numpy: aplicamos np.sum a la matriz y el parámetro que queremos sumar (axis=0 es columnas)

np.sum(mat,axis=0)           

array([55, 60, 65, 70, 75])

In [29]:
#Sin numpy: aplicamos suma a mat, pero solo a las columnas, desde la primera, la 0

mat.sum(axis=0)                

array([55, 60, 65, 70, 75])

*Resultado esperado:*


```python
array([55, 60, 65, 70, 75])
```

In [30]:
#Si quisiéramos sumar las filas, usaríamos axis=1

np.sum(mat,axis=1)                

array([ 15,  40,  65,  90, 115])

## Avanzado

#### Obtenga el rango de la siguiente matriz cuadrada:

```python
Z = np.random.uniform(0,1,(10,10))
```

*(Indicaciones: Al ser cuadrada, podemos analizar sus autovalores)*

In [37]:
#Z = np.random.uniform(0,1,(10,10))
#U, S, V = np.linalg.svd(Z) # Singular Value Decomposition
#rank = np.sum(S > 1e-10)
#print(rank)

In [38]:
#Generar la matriz
Z = np.random.uniform(0,1,(10,10))
Z

array([[0.82917084, 0.74731579, 0.36020309, 0.82495838, 0.07398358,
        0.91132986, 0.89629334, 0.44963861, 0.74942748, 0.47944729],
       [0.55398893, 0.32678183, 0.50347793, 0.07663891, 0.46870838,
        0.92503173, 0.35183479, 0.94483013, 0.5399133 , 0.3009407 ],
       [0.72770813, 0.61312791, 0.51000241, 0.02051147, 0.22339209,
        0.49113017, 0.61875525, 0.00354154, 0.49609437, 0.99308427],
       [0.37057091, 0.18952726, 0.61373021, 0.17624298, 0.5009957 ,
        0.92273685, 0.51856707, 0.34528265, 0.13083739, 0.7281229 ],
       [0.73485076, 0.91900826, 0.76916962, 0.28961538, 0.77019979,
        0.46634631, 0.09531246, 0.05928233, 0.78224503, 0.40683339],
       [0.7762922 , 0.2102001 , 0.56348906, 0.6368119 , 0.0275436 ,
        0.80875055, 0.4504075 , 0.64954253, 0.42986741, 0.24747449],
       [0.65767378, 0.56926128, 0.18069587, 0.51057234, 0.39332491,
        0.97404501, 0.512289  , 0.11573046, 0.55749649, 0.16224224],
       [0.67342792, 0.38592684, 0.3591023

In [39]:
#Calculamos autovalores
U,S,V=np.linalg.svd(Z)
rank=np.sum(S > 1e-10)
rank


10

#### Implemente el algoritmo k-NN (*k Nearest Neighbours*)

*Indicaciones: Este algoritmo de aprendizaje supervisado consiste en asignar, a cada elemento, la media de las labels de los k vecinos más cercanos que tenga dicho elemento.*


*Veámoslo sobre un ejemplo: Supongamos que tenemos una serie de variables comportamentales de estudiantes (visualizaciones, ediciones, creaciones y descargas):*

```python
array([[19,  7, 12,  4],
       [19,  0,  7,  9],
       [17, 12, 17,  6],
       [ 8, 10,  1, 12],
       [ 9,  6,  0, 15],
       [11, 18,  1, 14],
       [16,  8, 12,  1],
       [ 2, 13,  6, 17],
       [ 0,  7, 13,  8],
       [15,  9, 10, 15]])
```

*Asociado a estos datos, tenemos además una calificación del estudiante a final de curso:*

```python
array([[6],
       [4],
       [7],
       [4],
       [3],
       [9],
       [9],
       [5],
       [3],
       [4]])
```

*A los datos que usamos para tratar de estimar las calificaciones los llamaremos features, y a la nota en sí la label del problema. Cada fila es el registro de un alumno, por lo que entendemos que la información de los estudiantes la podemos representar en un espacio 4-dimensional.*

*Bajo estas circunstancias, el algoritmo sigue estos pasos:*

1.  *Para un cierto estudiante sin calificación, calculamos la distancia (en el mencionado espacio 4-dimensional) del estudiante sin calificar a cada uno de los calificados.*

2.  *Habiendo prefijado el parámetro k, escogemos las notas de los k estudiantes más cercanos.*

3.  *Hacemos la media (moda en caso discreto) de estos datos, y esa será la estimación que tengamos del alumno.*


In [ ]:
#Creamos función que, dados dos arrays 1D, nos devuelva la distancia euclídea de los mismos
def euclidean_distance(vec1, vec2):
  #Algunas comprobaciones para mejorar la búsqueda de errores en código son:
  #if (type(vec1)!=np.ndarray) | (type(vec2)!=np.ndarray):
  # raise ValueError('El formato de alguno de los vectores de entrada no es np.array.')
  #if vec1.shape!=vec2.shape:
  # raise ValueError('Los arrays de entrada no tienen la misma forma.')
  return np.sqrt(np.sum((vec1-vec2)**2, axis = -1))

In [ ]:
#Fijamos número de "vecinos" en los que basar la nota
k = 2

#Obtenemos features
features = np.array([[19,  7, 12,  4],
                     [19,  0,  7,  9],
                     [17, 12, 17,  6],
                     [ 8, 10,  1, 12],
                     [ 9,  6,  0, 15],
                     [11, 18,  1, 14],
                     [16,  8, 12,  1],
                     [ 2, 13,  6, 17],
                     [ 0,  7, 13,  8],
                     [15,  9, 10, 15]])

#Obtenemos label
label = np.array([[6],[4],[7],[4],[3],[9],[9],[5],[3],[4]])

#Fijamos un alumno nuevo
new_student = np.array([15, 6, 5, 2])

#Calculamos distancias
distances = np.zeros(label.shape) #Inicializamos un array para contener las distancias
for i in np.arange(label.shape[0]):
  distances[i] = euclidean_distance(features[i,:], new_student)

#Obtenemos los índices de los k vecinos más próximos
optimal_idx = np.argpartition(distances.reshape(-1), k)[:k]

#Mostramos resultado
label_new_student = np.round(np.mean(label[optimal_idx]),2)
print('La predicción para el nuevo estudiante es: {}'.format(label_new_student))

La predicción para el nuevo estudiante es: 7.5


## Ejercicio adicional
Juego de Adivinanzas con NumPy  
Instrucciones: El programa ha generado un número aleatorio entre 1 y 100.   
Tienes 10 intentos para adivinar el número. 
Después de cada intento, recibirás una pista si tu adivinanza es mayor o menor que el número.   
Si adivinas el número, el programa te felicitará y terminará.   
Si no adivinas el número en 10 intentos, el programa te dirá cuál era el número.    
Para salir del juego, escribe 'exit' en lugar de un número. 
Puedes usar Tkiner para hacer una interfaz gráfica. (opcional, a futuro se puede implementar si tienen tiempo el fin de semana) 

In [ ]:
#Importamos libreria
import random 

#Generar un número aleatorio entre 1 y 100
numero_aleatorio=random.randint(1,100)           #lo nombro para poder usarlo y compararlo con lo que el usuario introduzca
print(numero_aleatorio)                          #uso randint para incluir el 1 y el 100 en las posibilidades #luego le quito el print
print(type(numero_aleatorio))                    #quiero ver el tipo de dato, para asegurarme que es el mismo tipo que ingrese el usuario

#Creamos un contador para los intentos de adivinar el número
intento=0

#Bucle de respuesta al usuario
for intento in range (1,11):
    #Solicitamos al usuario que escribe su número
    respuesta_usuario=input("Introduce un número entre 1 al 100. Si aciertas el número secreto, ¡Te llevas el bote!. Si quieres parar el juego, escribe la palabra exit")
   
    #Revisamos si la respuesta es "exit" para parar el juego
    if respuesta_usuario=="exit":                
        print("Es una pena que no lo pruebes de nuevo, ¡Nos vemos la próxima vez!")
        break
    
    #Si el usuario pone algo distinto a "exit", convertimos su entrada en un número entero para poder compararlo posteriormente
    numero_usuario=int(respuesta_usuario)         #como el número alatorio es entero, necesitamos que el del usuario lo sea también
    print(numero_usuario)
    print(type(numero_usuario))                  
        
    if numero_usuario==numero_aleatorio:
        print("¡Felicidades, has ganado el bote!")
        break
    
        
    if numero_usuario!=numero_aleatorio:
        print(f"Has fallado, pero no te preocupes, te quedan",(10-intento),"intentos.")   #restaremos a 10 (máximo de intentos), el número de intentos ya hechos
        
    
    if intento==10:
        print("Se han acabado tus intentos, suerte la próxima vez")    #Para el final del bucle, ponemos un mensaje distinto




20
<class 'int'>
23
<class 'int'>
Has fallado, pero no te preocupes, te quedan 9 intentos.
45
<class 'int'>
Has fallado, pero no te preocupes, te quedan 8 intentos.
45
<class 'int'>
Has fallado, pero no te preocupes, te quedan 7 intentos.
75
<class 'int'>
Has fallado, pero no te preocupes, te quedan 6 intentos.
46
<class 'int'>
Has fallado, pero no te preocupes, te quedan 5 intentos.
42
<class 'int'>
Has fallado, pero no te preocupes, te quedan 4 intentos.
46
<class 'int'>
Has fallado, pero no te preocupes, te quedan 3 intentos.
75
<class 'int'>
Has fallado, pero no te preocupes, te quedan 2 intentos.
71
<class 'int'>
Has fallado, pero no te preocupes, te quedan 1 intentos.
46
<class 'int'>
Has fallado, pero no te preocupes, te quedan 0 intentos.
Se han acabado tus intentos, suerte la próxima vez
