## Numpy Indexado y filtrado

Dada la siguiente matriz, realice las operaciones pertinentes para obtener la salida que se pide:

In [4]:
import numpy as np

mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

#### **Ejercicio 1:** Obtener el siguiente resultado:

```
array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])
```

In [ ]:
 #De mat, quiero las filas 2,3,4 (no quiero la línea 0)
 #Además quiero los números en las posiciones de la 1 al final (no quiero la posición 0)

mat[[2,3,4],1:]                      

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [ ]:
#Otra forma de hacerlo: selecciona las filas desde la fila en posición 2 y todos los valores de las columnas desde el valor en posición 1

mat[2:,1:]                

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

#### **Ejercicio 2:** Obtener el siguiente resultado:

```
20
```

In [ ]:
#De la fila 3, quiero la posición 4

mat1=mat[[3],4]     
mat1  

array([20])

In [ ]:
#Otra forma de hacerlo: Fila 3,columna 4

mat[3,4]


20

#### **Ejercicio 3:** Obtener el siguiente resultado:

```
array([[ 2],
       [ 7],
       [12]])
```


In [ ]:
#De las filas 0,1,2, devuélve la posición 1
#Usamos reshape() para devolverlo en forma de matriz

mat[[0,1,2],1].reshape(3,1)                   

array([[ 2],
       [ 7],
       [12]])

In [6]:
#Otra opción:seleccionar las 3 primeras filas (0,1,2) y las columnas de la 1 a la 2 (la segunda nunca entra, así que es solo delvolverá la del índice 1)

mat[:3,1:2]          

array([[ 2],
       [ 7],
       [12]])

In [5]:
#Otra opción: selecciona las columnas de la 0 a la 3 (0,1,2) y la columna en el índice 1

mat[0:3,[1]]              

array([[ 2],
       [ 7],
       [12]])

#### **Ejercicio 4:** Obtener el siguiente resultado:

```
array([21, 22, 23, 24, 25])
```

In [ ]:
#Obtener la fila 4

mat[4]           

array([21, 22, 23, 24, 25])

#### **Ejercicio 5:** Obtener el siguiente resultado:

```python
array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])
```


In [ ]:
#obtener las filas 3 y 4, de principio a fin (queremos todos los números de las filas así que solo ponemos dos puntos) 

mat[[3,4],:]                  

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

### Realice los siguiente cálculos:

#### **Ejercicio 6:** Obtenga la suma de todos los valores de la matriz


In [ ]:
#Método corto con numpy: usando función sum() de la matriz

np.sum(mat)                             

325

In [7]:
 #Método largo
 
 #Iniciar contador
suma=0                                        

for fila in mat:                  #pasar por cada fila
    for elemento in fila:         #pasar por cada elemento de cada fila
        suma=suma+elemento        #sumar cada elemento a la suma inicial (suma)
            
 
print(suma)                       #Mostrar resultado

325


#### **Ejercicio 7:** Calcule la desviación típica de los valores de la matriz

In [ ]:
 #Método cortocon numpy: usando la función std() de la matriz

np.std(mat)                            

7.211102550927978

#### **Ejercicio 8:** Sume los valores por columnas

*Resultado esperado:*


```python
array([55, 60, 65, 70, 75])
```

In [ ]:
#Con numpy: aplicamos np.sum a la matriz y el parámetro que queremos sumar (axis=0 es columnas)

np.sum(mat,axis=0)           

array([55, 60, 65, 70, 75])

In [ ]:
#Sin numpy: aplicamos suma a mat, pero solo a las columnas, desde la primera, la 0

mat.sum(axis=0)                

array([55, 60, 65, 70, 75])